# operations 
a=int(input("Enter first number:"))
b=int(input("Enter second number:"))
print("Addition:",a+b)
print("Subtraction:",b-a)
print("Multiplication:",a*b)    
print("Division:",b/a)
print("Floor Division:",b//a)   
print("Modulus:",b%a)
print("arthmetic operations")